### ISSUE TITLE
obsidian-vox-backend repo currently not visible

### ISSUE THREAD

**Issue by josiahseaman** [vincentbavitz/obsidian-vox#1]
Hello and thank you for making Obsidian Vox.
Your documentation points to the backend repo which is currently not visible. Is this possibly a private repo?

https://github.com/vincentbavitz/obsidian-vox-backend

**Comment by vincentbavitz** [comment]
Hey @josiahseaman . I've made a public endpoint now for the plugin so that you don't have to set up your own back-end.

And a self-hosted backend option will be available as soon as I can find some time. :)
