### ISSUE TITLE
Does the plugin work on mobile? 

### ISSUE THREAD

**Issue by tprotopopescu** [vincentbavitz/obsidian-vox#6]
On my phone (samsung note20) I cannot install this plugin, it says it does not support my device. The description of the plugin makes it seem like it should work (the "mobile only" example set up). Is it just my device or am I missing something?

**Comment by vincentbavitz** [comment]
Hey @tprotopopescu - you're correct that currently the plugin doesn't work on mobile. I'll update the README to reflect this when I can. Many thanks.

**Comment by tprotopopescu** [comment]
Okay, thanks.
